### ISSUE TITLE
Egg turner Picture

### ISSUE THREAD

**Issue by freakezoid1604** [anwofis/simple_incubator#1]
Hi
can you show some detailed picture of the egg turner?
I will try the code, but i need the library's.
I have this lcd https://www.tme.eu/en/details/eaw204-bnled/lcd-alphanumeric-displays/electronic-assembly/ea-w204-bnled/ and i  plan to use this.
thank you

Hallo
Könntest du eventuell detaillierte Bilder von deinem Ei Wender einstellen? Sieht sehr interessant aus.
Wäre es möglich die passenden Bibliotheken bzw. das ganze projekt zu bekommen?
Ich habe dieses LCD https://www.tme.eu/en/details/eaw204-bnled/lcd-alphanumeric-displays/electronic-assembly/ea-w204-bnled/ und würde es gern auf dieses umbauen. 

Danke dir

**Comment by anwofis** [comment]
Hello,

i'm planning to write an update some time as i improved the egg turner a little. 

Most libraries can be installed via the Arduino IDE. 
INTERVAL.h is from here: https://forum.arduino.cc/index.php?topic=413734.0

As LCD i'm using a cheap standard 2004 LCD with I2C Backpack from eBay. Yours is quite expensive!  

Best regards, 
anwofis

**Comment by anwofis** [comment]
Hello,

i wrote an update with better pictures and some links.
I'll close this issue soon if there are no more questions.

Best regards,

anwofis

**Comment by anwofis** [comment]
Closed.
